"use client";

import { useEffect, useMemo, useState } from "react";
import { checklist, days, event, Lang, locations, scienceAgenda } from "./event-data";
import { ContactsSection, IstanbulSection, RestaurantsSection } from "./experience-enhancements";

const A = (path: string) => `${typeof window !== "undefined" && window.location.pathname.startsWith("/Istanubul-First") ? "/Istanubul-First" : ""}${path}`;
const activityIcon = { travel: "↗", dining: "◇", science: "+", social: "✦", hotel: "⌂", free: "○" };
const copy = {
  en: { start:"Start the Experience",skip:"Skip introduction",until:"Until the experience",live:"FIRST is Live",thanks:"Thank you for being part of FIRST",welcome:"Welcome to a journey where science, connection and Istanbul come together.",nextStep:"Your next step",personalize:"Personalize my welcome",name:"Preferred name",save:"Save",program:"Live Program",journey:"Your Journey",science:"Scientific Symposium",speakers:"Meet Our Speakers",locations:"Location Companion",before:"Travel Ready",support:"Experience Team",faq:"FAQ",moments:"Our Moments",explore:"Explore the program",calendar:"Add to Calendar",route:"Navigate",addSession:"Add to Calendar",now:"Now",next:"Next",completed:"Completed",upcoming:"Upcoming",today:"Today",meeting:"Meeting point",checklist:"Checklist",reset:"Reset checklist",addItem:"Add personal item",install:"Add to Home Screen",offline:"Core event information is available offline.",all:"All",hotel:"Hotel",dining:"Dining",scientific:"Scientific",social:"Social",copy:"Copy link",share:"Share",viewSession:"View session",close:"Close" },
  ar: { start:"ابدأ التجربة",skip:"تخطّي المقدمة",until:"متبقي على التجربة",live:"FIRST مباشرة",thanks:"شكراً لأنك كنت جزءاً من FIRST",welcome:"أهلاً بك في رحلة يجتمع فيها العلم والتواصل وسحر إسطنبول.",nextStep:"خطوتك التالية",personalize:"خصص رسالة الترحيب",name:"الاسم المفضل",save:"حفظ",program:"البرنامج المباشر",journey:"رحلتك",science:"الندوة العلمية",speakers:"تعرّف على محاضرينا",locations:"دليل المواقع",before:"جاهز للسفر",support:"فريق التجربة",faq:"الأسئلة الشائعة",moments:"لحظاتنا",explore:"استعرض البرنامج",calendar:"أضف إلى التقويم",route:"افتح الخريطة",addSession:"أضف إلى التقويم",now:"الآن",next:"التالي",completed:"مكتمل",upcoming:"قادم",today:"اليوم",meeting:"نقطة اللقاء",checklist:"قائمة التجهيز",reset:"إعادة ضبط القائمة",addItem:"أضف بنداً شخصياً",install:"أضف للشاشة الرئيسية",offline:"المعلومات الأساسية للفعالية متاحة دون إنترنت.",all:"الكل",hotel:"الفندق",dining:"المطاعم",scientific:"العلمي",social:"الاجتماعي",copy:"نسخ الرابط",share:"مشاركة",viewSession:"عرض الجلسة",close:"إغلاق" }
};
type Phase = "before"|"live"|"after";
type ActivityState = "completed"|"now"|"next"|"upcoming";
function eventPhase(now:Date):Phase { if(now<new Date(event.start))return"before";if(now<=new Date(event.end))return"live";return"after"; }
function activityBounds(di:number,time:string){const [s,e=s]=time.replace(/\s/g,"").split(/[–-]/);const make=(v:string)=>{const [h,m]=v.split(":").map(Number);return new Date(Date.UTC(2026,8,15+di,h-3,m||0))};return [make(s),make(e)] as const}
function activityState(di:number,ai:number,now:Date):ActivityState{const[s,e]=activityBounds(di,days[di].activities[ai].time);if(now>e)return"completed";if(now>=s&&now<=e)return"now";const next=days.flatMap((d,dn)=>d.activities.map((_,an)=>({dn,an,start:activityBounds(dn,d.activities[an].time)[0]}))).filter(x=>x.start>now).sort((a,b)=>+a.start-+b.start)[0];return next?.dn===di&&next?.an===ai?"next":"upcoming"}
function makeIcs(title:string,start:Date,end:Date,location=""){const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const clean=(s:string)=>s.replace(/[,;]/g,"\\$&");return`data:text/calendar;charset=utf-8,${encodeURIComponent(`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Dar Aldawa//FIRST Istanbul 2026//EN\nBEGIN:VEVENT\nUID:${stamp(start)}@first-istanbul\nDTSTAMP:${stamp(new Date())}\nDTSTART:${stamp(start)}\nDTEND:${stamp(end)}\nSUMMARY:${clean(title)}\nLOCATION:${clean(location)}\nEND:VEVENT\nEND:VCALENDAR`)}`}

export default function Home(){
  const[lang,setLang]=useState<Lang>("en"),[started,setStarted]=useState(false),[menu,setMenu]=useState(false),[day,setDay]=useState(0),[now,setNow]=useState(new Date());
  const[guestName,setGuestName]=useState(""),[nameDraft,setNameDraft]=useState(""),[checked,setChecked]=useState<number[]>([]),[customItems,setCustomItems]=useState<string[]>([]),[customDone,setCustomDone]=useState<number[]>([]),[customDraft,setCustomDraft]=useState("");
  const[locationFilter,setLocationFilter]=useState("all"),[active,setActive]=useState("home"),[progress,setProgress]=useState(0),[speaker,setSpeaker]=useState<"suliman"|"feras"|null>(null),[installPrompt,setInstallPrompt]=useState<(Event&{prompt?:()=>Promise<void>})|null>(null);
  const t=copy[lang],phase=eventPhase(now);
  useEffect(()=>{try{const l=localStorage.getItem("first-lang") as Lang|null;if(l==="en"||l==="ar")setLang(l);const n=localStorage.getItem("first-name")||"";setGuestName(n);setNameDraft(n);setChecked(JSON.parse(localStorage.getItem("first-checklist")||"[]"));setCustomItems(JSON.parse(localStorage.getItem("first-custom-items")||"[]"));setCustomDone(JSON.parse(localStorage.getItem("first-custom-done")||"[]"));const q=new URLSearchParams(location.search).get("name");if(q){setGuestName(q.slice(0,60));setNameDraft(q.slice(0,60))}}catch{}if("serviceWorker"in navigator)navigator.serviceWorker.register(A("/sw.js"),{scope:A("/")}).catch(()=>undefined);const capture=(e:Event)=>{e.preventDefault();setInstallPrompt(e as Event&{prompt:()=>Promise<void>})};addEventListener("beforeinstallprompt",capture);return()=>removeEventListener("beforeinstallprompt",capture)},[]);
  useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";localStorage.setItem("first-lang",lang)},[lang]);
  useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(phase==="live")setDay(Math.min(3,Math.max(0,Number(new Intl.DateTimeFormat("en-GB",{day:"numeric",timeZone:"Europe/Istanbul"}).format(now))-15)))},[phase]);
  useEffect(()=>{const ids=["home","journey","program","science","speakers","locations","istanbul","restaurants","before","support","faq"];const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:"-35% 0px -55%"});ids.forEach(id=>{const n=document.getElementById(id);if(n)obs.observe(n)});const scroll=()=>setProgress(Math.min(100,Math.round(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100)));addEventListener("scroll",scroll,{passive:true});scroll();return()=>{obs.disconnect();removeEventListener("scroll",scroll)}},[started]);
  const countdown=useMemo(()=>{const target=phase==="before"?new Date(event.start):phase==="live"?new Date(event.end):now,d=Math.max(0,+target-+now);return[Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60]},[now,phase]);
  const currentOrNext=useMemo(()=>{for(let di=0;di<days.length;di++)for(let ai=0;ai<days[di].activities.length;ai++){const state=activityState(di,ai,now);if(state==="now"||state==="next")return{di,ai,state,item:days[di].activities[ai]}}return null},[now]);
  const nav=[["home",phase==="live"?t.today:"Welcome"],["journey",t.journey],["program",t.program],["science",t.science],["speakers",t.speakers],["locations",t.locations],["istanbul",lang==="ar"?"أساسيات إسطنبول":"Istanbul Essentials"],["restaurants",lang==="ar"?"مذاقات إسطنبول":"Dining Journal"],["before",t.before],["support",t.support],["faq",t.faq]];
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)},persist=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value));
  const toggleCheck=(i:number)=>{const n=checked.includes(i)?checked.filter(x=>x!==i):[...checked,i];setChecked(n);persist("first-checklist",n)},saveName=()=>{const n=nameDraft.trim().slice(0,60);setGuestName(n);localStorage.setItem("first-name",n)},resetChecklist=()=>{if(confirm(lang==="ar"?"إعادة ضبط كل التقدم؟":"Reset all checklist progress?")){setChecked([]);setCustomDone([]);persist("first-checklist",[]);persist("first-custom-done",[])}},addCustom=()=>{const item=customDraft.trim().slice(0,80);if(!item)return;const n=[...customItems,item];setCustomItems(n);setCustomDraft("");persist("first-custom-items",n)};
  const total=checklist.length+customItems.length,done=checked.length+customDone.length;
  return <main className={`site-shell phase-${phase}`}>
    <a className="skip-link" href="#home">Skip to content</a>
    <div className={`opening opening--theme ${started?"opening--closed":""}`} aria-hidden={started}><div className="opening-sequence"><span>AMMAN</span><i>→</i><span>ISTANBUL</span><small>SCIENCE · CONNECTION · EXPERIENCE</small></div><div className="opening-countdown" aria-live="polite"><span>{phase==="after"?t.thanks:phase==="live"?t.live:t.until}</span><div className="opening-countdown-units">{countdown.map((v,i)=><strong key={i}><b>{String(v).padStart(2,"0")}</b><small>{["days","hours","minutes","seconds"][i]}</small></strong>)}</div></div><button className="opening-enter" onClick={()=>setStarted(true)}><span>{t.start}</span><i>→</i></button><button className="opening-skip" onClick={()=>setStarted(true)}>{t.skip}</button></div>
    {menu&&<button className="menu-backdrop" aria-label={t.close} onClick={()=>setMenu(false)}/>}<aside className={`sidebar floating-dropdown ${menu?"sidebar--open":""}`} aria-label="Main navigation"><div className="floating-menu-head"><img src={A("/assets/dar-aldawa-logo-transparent.png")} alt="Dar Aldawa"/><b>FIRST · ISTANBUL 2026</b><button onClick={()=>setMenu(false)} aria-label={t.close}>×</button></div><nav>{nav.map(([id,label],i)=><button className={active===id?"active":""} key={id} onClick={()=>go(id)}><span>{String(i+1).padStart(2,"0")}</span>{label}</button>)}</nav><div className="sidebar-progress"><span style={{width:`${progress}%`}}/><b>{progress}%</b></div><div className="sidebar-foot"><span>15—18 SEPTEMBER</span><button className="lang" onClick={()=>setLang(lang==="en"?"ar":"en")}>{lang==="en"?"ع":"EN"}</button></div></aside><button className={`floating-menu-button ${menu?"is-open":""}`} onClick={()=>setMenu(v=>!v)} aria-expanded={menu}><span/><span/><span/><b>{active.toUpperCase()}</b></button>
    <div className="page">
      <section id="home" className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="hero-orbit hero-orbit--one"/><div className="hero-orbit hero-orbit--two"/><div className="hero-content reveal"><p className="eyebrow">DAR ALDAWA PRESENTS · ISTANBUL 2026</p><img className="hero-first-logo" src={A("/assets/first-logo.png")} alt="FIRST"/><h1><small>{event.tagline}</small></h1><p className="hero-welcome">{guestName?`${lang==="ar"?"أهلاً بك دكتور":"Welcome, Dr."} ${guestName}`:t.welcome}</p><div className="hero-actions"><button className="button button--bright" onClick={()=>go(phase==="live"?"live-hub":"program")}><span className="button-icon">▶</span>{t.explore}</button><a className="button button--glass" href={A("/FIRST-Istanbul-2026.ics")}><span className="button-icon">▣</span>{t.calendar}</a></div></div><div className="phase-badge"><span className="pulse"/><b>{phase==="before"?"ANTICIPATION":phase==="live"?t.live:"MEMORIES"}</b></div><div className="hero-metrics" aria-label="Event at a glance"><article><span>04</span><small>{lang==="ar"?"أيام مميزة":"CURATED DAYS"}</small></article><article><span>02</span><small>{lang==="ar"?"خبراء علميون":"MEDICAL FACULTY"}</small></article><article><span>07</span><small>{lang==="ar"?"وجهات مختارة":"SIGNATURE PLACES"}</small></article><article><span>01</span><small>{lang==="ar"?"تجربة واحدة":"CONNECTED EXPERIENCE"}</small></article></div></section>
      <section id="live-hub" className="live-hub" aria-live="polite"><div className="live-hub-title"><span>{phase==="live"?t.live:t.nextStep}</span><h2>{new Intl.DateTimeFormat(lang==="ar"?"ar-JO":"en-GB",{weekday:"long",day:"numeric",month:"long",timeZone:"Europe/Istanbul"}).format(now)}</h2><p>{new Intl.DateTimeFormat(lang==="ar"?"ar-JO":"en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"Europe/Istanbul"}).format(now)} · Istanbul</p></div><div className="live-hub-grid"><article><i className="hub-icon">◉</i><small>{currentOrNext?.state==="now"?t.now:t.next}</small><b>{currentOrNext?currentOrNext.item[lang]:phase==="after"?t.thanks:lang==="ar"?"جهّز وثائق السفر":"Review your travel checklist"}</b><span>{currentOrNext?.item.time||event.dates}</span></article><article><i className="hub-icon">⌖</i><small>{t.meeting}</small><b>{currentOrNext?.item.en.includes("lobby")?"Hilton lobby":currentOrNext?.item.en.includes("Gate 13")?"Airport · Gate 13":"See live program"}</b><button onClick={()=>go("program")}>{t.program} ↗</button></article><article><i className="hub-icon">✓</i><small>{t.checklist}</small><b>{done}/{total}</b><span>{Math.round(done/Math.max(1,total)*100)}% complete</span><button onClick={()=>go("before")}>{t.nextStep} ↗</button></article><article className="live-help"><i className="hub-icon">＋</i><small>{t.support}</small><b>112</b><span>{lang==="ar"?"للطوارئ فقط":"Emergency only"}</span><button onClick={()=>go("support")}>{t.support} ↗</button></article></div></section>
      {!guestName&&<section className="personalize"><div><small>LOCAL · PRIVATE · OPTIONAL</small><h2>{t.personalize}</h2><p>{lang==="ar"?"يُحفظ الاسم على جهازك فقط ولا يتم إرساله لأي جهة.":"Your name stays on this device and is never uploaded."}</p></div><div><label htmlFor="guest-name">{t.name}</label><input id="guest-name" value={nameDraft} onChange={e=>setNameDraft(e.target.value)} maxLength={60}/><button onClick={saveName}>{t.save}</button></div></section>}
      <section id="journey" className="section section--light"><SectionHead index="02" kicker="AMMAN → ISTANBUL" title={t.journey} sub={lang==="ar"?"تفاصيل الرحلة المؤكدة في مكان واحد.":"Your confirmed journey details in one calm place."}/><div className="route-infographic"><div><span>AMM</span><small>AMMAN</small></div><div className="route-track"><i>✈</i><b>AMMAN → ISTANBUL</b><small>YOUR FIRST JOURNEY</small></div><div><span>IST</span><small>ISTANBUL</small></div></div><div className="boarding-grid">{[{label:lang==="ar"?"رحلة الذهاب":"Outbound journey",from:"AMMAN",to:"ISTANBUL",date:"15 SEP 2026"},{label:lang==="ar"?"رحلة العودة":"Return journey",from:"ISTANBUL",to:"AMMAN",date:"18 SEP 2026"}].map((f,i)=><article className="boarding" key={f.label}><div className="boarding-top"><span>{f.label}</span><b>FIRST / 0{i+1}</b></div><div className="boarding-route"><div><small>FROM</small><strong>{f.from}</strong></div><div className="route-line"><span>✈</span></div><div><small>TO</small><strong>{f.to}</strong></div></div><div className="boarding-meta"><div><small>DATE</small><b>{f.date}</b></div><div><small>FLIGHT</small><b>TBC</b></div><div><small>TIME</small><b>TBC</b></div><div><small>BAGGAGE</small><b>TBC</b></div></div><p>{lang==="ar"?"سيتم تحديث التفاصيل فور اعتمادها.":"Details will update as soon as they are confirmed."}</p></article>)}</div><div className="arrival-note"><span>13</span><div><b>{lang==="ar"?"نقطة اللقاء عند الوصول":"Arrival meeting point"}</b><p>{lang==="ar"?"الاستقبال من بوابة رقم 13 بين 11:30 و12:30":"Airport pick-up at Gate 13 between 11:30 and 12:30"}</p></div></div></section>
      <section id="program" className="section section--dark calendar-program"><SectionHead index="03" kicker="15—18 SEPTEMBER" title={t.program} sub={lang==="ar"?"اختر التاريخ؛ تتبدل الحالات تلقائياً أثناء الفعالية.":"Choose a date; live states update automatically during the event."}/><div className="day-tabs calendar-tabs" role="tablist">{days.map((d,i)=><button role="tab" aria-selected={day===i} className={day===i?"active":""} onClick={()=>setDay(i)} key={d.date}><span>{d.date.split(" ")[0]}</span><b>{d.date.split(" ")[1]}</b><small>{d.label[lang]}</small><i>0{i+1}</i></button>)}</div><div className="calendar-page" key={day}><div className="calendar-page-head"><span>DAY 0{day+1}</span><div><b>{days[day].date}</b><small>{days[day].label[lang]}</small></div></div><div className="timeline">{days[day].activities.map((a,i)=>{const state=activityState(day,i,now),[start,end]=activityBounds(day,a.time);return<article className={`timeline-item type-${a.type} state-${state}`} key={`${a.time}-${i}`}><div className="time">{a.time}</div><div className="timeline-dot">{activityIcon[a.type]}</div><div className="activity"><span className="state-label">{t[state]}</span><b>{a[lang]}</b><small>{a.type.toUpperCase()}</small><div className="activity-actions">{a.map&&<a href={a.map} target="_blank" rel="noreferrer">{t.route} ↗</a>}<a download={`FIRST-${day+1}-${i+1}.ics`} href={makeIcs(a.en,start,end)}>{t.addSession} +</a></div></div></article>})}</div></div><div className="program-actions"><a className="button button--bright" href={A("/FIRST-Istanbul-2026.ics")}>{t.calendar}</a><button className="button button--outline" onClick={()=>print()}>PDF</button></div></section>
      <section id="science" className="section section--mint"><SectionHead index="03A" kicker="WEDNESDAY · 16 SEPTEMBER 2026" title={t.science} sub="Crystal Ballroom · M2 Floor"/><div className="science-stats"><article><i>◉</i><span>02</span><b>{lang==="ar"?"محاضرتان علميتان":"Scientific Talks"}</b></article><article><i>?</i><span>02</span><b>{lang==="ar"?"نقاشان تفاعليان":"Interactive Q&A"}</b></article><article><i>☕</i><span>01</span><b>{lang==="ar"?"استراحة تواصل":"Networking Break"}</b></article><article><i>◷</i><span>180</span><b>{lang==="ar"?"دقيقة مركزة":"Focused Minutes"}</b></article></div><div className="science-wrap"><div className="science-list">{scienceAgenda.map((a,i)=><div className={`science-row science-${a.type}`} id={`science-${i}`} key={i}><time>{a.time}</time><span>{a[lang]}</span></div>)}</div><button className="agenda-poster" onClick={()=>open(A("/assets/scientific-agenda.jpg"),"_blank")}><img src={A("/assets/scientific-agenda.jpg")} alt="Scientific symposium agenda"/><span>{lang==="ar"?"عرض الأجندة الأصلية":"View original agenda"} ↗</span></button></div></section>
      <section id="speakers" className="section section--light"><SectionHead index="04" kicker="DISTINGUISHED SPEAKERS" title={t.speakers} sub={lang==="ar"?"خبرات تجمع بين الممارسة السريرية والدليل العلمي.":"Clinical leadership meets evidence-led practice."}/><div className="speakers-grid"><Speaker image={A("/assets/dr-suliman-soudi.jpg")} name="Dr. Suliman Soudi" role={lang==="ar"?"استشاري الأنف والأذن والحنجرة":"Ear, Nose & Throat Consultant"} title="GERD Management: Broadening Recognition, Enhancing Care" onOpen={()=>setSpeaker("suliman")} view={t.viewSession}/><Speaker image={A("/assets/dr-feras-zuriekat.jpg")} name="Dr. Feras Zuriekat, MD, MRCP (UK)" role={lang==="ar"?"استشاري أمراض الجهاز الهضمي والكبد":"Consultant in Gastroenterology & Hepatology"} title="GERD Management: Integrating Evidence, Optimizing Outcomes" onOpen={()=>setSpeaker("feras")} view={t.viewSession}/></div></section>
      <section id="locations" className="section section--navy"><SectionHead index="05" kicker="YOUR ISTANBUL MAP" title={t.locations} sub={lang==="ar"?"كل وجهة في البرنامج مع موعدها ورابطها المعتمد.":"Every programme destination with its date and verified map link."}/><div className="location-filters">{[["all",t.all],["hotel",t.hotel],["dining",t.dining],["science",t.scientific],["social",t.social]].map(([key,label])=><button className={locationFilter===key?"active":""} onClick={()=>setLocationFilter(key)} key={key}>{label}</button>)}</div><div className="location-grid">{locations.filter(l=>locationFilter==="all"||l.kind===locationFilter).map((l,i)=><article className="location-card" key={l.en}><img className="location-card-photo" src={l.image} alt={l[lang]} loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=A("/assets/hero-istanbul.png")}}/><span className="location-card-overlay"/><span className={`pin pin--${l.kind}`}>0{i+1}</span><div className="location-card-content"><small>{l.kind.toUpperCase()}</small><b>{l[lang]}</b><em>{event.dates}</em><div><a href={l.map} target="_blank" rel="noreferrer">{t.route} ↗</a><button onClick={()=>navigator.clipboard?.writeText(l.map)}>{t.copy}</button><button onClick={()=>navigator.share?.({title:l.en,url:l.map})}>{t.share}</button></div></div></article>)}</div></section>
      <IstanbulSection lang={lang}/><RestaurantsSection lang={lang}/>
      <section id="before" className="section section--light"><SectionHead index="08" kicker="TRAVEL READY" title={t.before} sub={lang==="ar"?"يتم حفظ تقدمك على هذا الجهاز فقط.":"Your progress stays safely on this device."}/><div className="checklist"><div className="check-progress"><span style={{width:`${Math.round(done/Math.max(1,total)*100)}%`}}/><b>{done}/{total}</b></div>{[["DOCUMENTS",[0,1,2]],["PACKING",[3,4,5]],["EVENT READINESS",[6,7,8]]].map(([group,indexes])=><div className="check-group" key={String(group)}><h3>{String(group)}</h3>{(indexes as number[]).map(i=><button role="checkbox" aria-checked={checked.includes(i)} className={checked.includes(i)?"done":""} onClick={()=>toggleCheck(i)} key={checklist[i].en}><span className="check-box" aria-hidden="true">{checked.includes(i)?"✓":""}</span><b>{checklist[i][lang]}</b></button>)}</div>)}{customItems.length>0&&<div className="check-group"><h3>PERSONAL</h3>{customItems.map((item,i)=><button role="checkbox" aria-checked={customDone.includes(i)} className={customDone.includes(i)?"done":""} onClick={()=>{const n=customDone.includes(i)?customDone.filter(x=>x!==i):[...customDone,i];setCustomDone(n);persist("first-custom-done",n)}} key={`${item}-${i}`}><span className="check-box" aria-hidden="true">{customDone.includes(i)?"✓":""}</span><b>{item}</b></button>)}</div>}<div className="check-custom"><input value={customDraft} onChange={e=>setCustomDraft(e.target.value)} placeholder={t.addItem} maxLength={80}/><button onClick={addCustom}>＋</button></div><button className="reset-button" onClick={resetChecklist}>{t.reset}</button></div></section>
      <ContactsSection lang={lang} onShareLocation={()=>{if(!confirm(lang==="ar"?"سيتم فتح واتساب برسالة تحتوي رابط موقعك الحالي. متابعة؟":"WhatsApp will open with a link to your current location. Continue?"))return;navigator.geolocation?.getCurrentPosition(({coords})=>open(`https://wa.me/?text=${encodeURIComponent(`My current location: https://maps.google.com/?q=${coords.latitude},${coords.longitude}`)}`,"_blank","noopener,noreferrer"))}}/>
      <section id="faq" className="section section--light"><SectionHead index="10" kicker="GOOD TO KNOW" title={t.faq} sub={lang==="ar"?"إجابات سريعة للمعلومات الأهم.":"Fast answers to the details that matter."}/><div className="faq">{(lang==="ar"?[["أين وموعد التجمع عند الوصول؟","الاستقبال من بوابة رقم 13 من 11:30 إلى 12:30 يوم 15 سبتمبر."],["متى تُقام الندوة العلمية؟","الأربعاء 16 سبتمبر في قاعة Crystal، طابق M2."],["هل يمكن استخدام الموقع دون إنترنت؟","بعد فتح الموقع مرة واحدة تبقى المعلومات الأساسية متاحة عند ضعف الاتصال."]]:[["Where and when is the arrival meeting point?","Airport pick-up is at Gate 13 from 11:30 to 12:30 on 15 September."],["When is the symposium?","Wednesday, 16 September in Crystal Ballroom, M2."],["Can I use the site offline?","After one visit, core event information remains available with weak connectivity."]]).map(([q,a],i)=><details key={i}><summary><span>0{i+1}</span>{q}</summary><p>{a}</p></details>)}</div></section>
      <footer><div className="footer-brand"><img src={A("/assets/dar-aldawa-logo-transparent.png")} alt="Dar Aldawa"/><b>FIRST · Steps to Effective Treatment</b></div><p>15—18 SEPTEMBER 2026 · ISTANBUL</p><div className="sources"><a href="https://www.112.gov.tr/" target="_blank" rel="noreferrer">Türkiye 112 ↗</a><a href="https://www.timeanddate.com/time/zone/turkey/istanbul" target="_blank" rel="noreferrer">Istanbul time ↗</a></div></footer>
    </div>
    <nav className="bottom-nav" aria-label="Quick navigation"><button onClick={()=>go("live-hub")}>◉<span>{t.today}</span></button><button onClick={()=>go("program")}>☷<span>{t.program}</span></button><button onClick={()=>go("locations")}>⌖<span>{t.locations}</span></button><button onClick={()=>go("support")}>＋<span>{t.support}</span></button></nav>{installPrompt&&<button className="install-hint" onClick={async()=>{await installPrompt.prompt?.();setInstallPrompt(null)}}>{t.install} ＋</button>}<div className="offline-note" role="status">{t.offline}</div>
    {speaker&&<div className="modal" role="dialog" aria-modal="true" aria-label="Speaker profile"><button className="modal-backdrop" onClick={()=>setSpeaker(null)} aria-label={t.close}/><div className="speaker-modal"><button onClick={()=>setSpeaker(null)} aria-label={t.close}>×</button><img src={speaker==="suliman"?A("/assets/dr-suliman-soudi.jpg"):A("/assets/dr-feras-zuriekat.jpg")} alt=""/><div><small>FIRST SPEAKER</small><h2>{speaker==="suliman"?"Dr. Suliman Soudi":"Dr. Feras Zuriekat, MD, MRCP (UK)"}</h2><p>{speaker==="suliman"?"Ear, Nose & Throat Consultant · Formerly at Royal Medical Services · Fellow of the Royal College of Surgeons, UK · Diploma in Ear & Cochlear Implant Surgery, Oklahoma · Bachelor of Medicine and Surgery, Liverpool":"Consultant in Gastroenterology & Hepatology · Head of Gastroenterology & Hepatology at Abdali Hospital · University of Dundee Medical School graduate, 1995 · Prize for Best Overseas Student · MRCP (UK), 2001"}</p><button onClick={()=>{setSpeaker(null);go("science")}}>{t.viewSession} ↗</button></div></div></div>}
  </main>
}
function SectionHead({index,kicker,title,sub}:{index:string;kicker:string;title:string;sub:string}){const icons:Record<string,string>={"02":"✈","03":"▣","03A":"＋","04":"◉","05":"⌖","08":"✓","10":"?"};return<div className="section-head"><span className="section-index">{index}</span><i className="section-icon">{icons[index]||"✦"}</i><div><small>{kicker}</small><h2>{title}</h2><p>{sub}</p></div></div>}
function Speaker({image,name,role,title,onOpen,view}:{image:string;name:string;role:string;title:string;onOpen:()=>void;view:string}){return<article className="speaker"><div className="speaker-photo"><img src={image} alt={name}/></div><div className="speaker-copy"><span>FIRST SPEAKER</span><h3>{name}</h3><p className="speaker-role">{role}</p><blockquote>“{title}”</blockquote><button className="text-button" onClick={onOpen}>{view} ↗</button></div></article>}
