"use client";

import { useEffect, useMemo, useState } from "react";
import { checklist, days, event, Lang, locations, scienceAgenda } from "./event-data";
import { ContactsSection, IstanbulSection, RestaurantsSection } from "./experience-enhancements";

const copy = {
  en: {
    start: "Start the Experience", opening: "Your Istanbul Experience Starts Here", welcome: "Welcome to a journey where science, connection and Istanbul come together.",
    explore: "Explore the program", calendar: "Add event to calendar", days: "Days", talks: "Scientific talks", city: "City", stay: "Your stay", letter: "Welcome Letter",
    journey: "The Journey Begins Here", program: "The Signature Program", science: "Scientific Symposium", speakers: "Meet the Speakers", locations: "Your Location Companion",
    hotel: "Your Stay", before: "Before You Go", essentials: "Istanbul Essentials", support: "Support & Contacts", faq: "Frequently Asked Questions", gallery: "Our Moments Together", home: "Experience",
    note: "Programme confirmed · Flight and contact details will be shared soon", download: "Download original letter", close: "Close", route: "Open in Google Maps",
    share: "Share this experience", print: "Save program as PDF", flightPending: "Flight details to be updated", outbound: "Outbound journey", return: "Return journey", origin: "Jordan", destination: "Istanbul",
    eventDay: "Wednesday · 16 September 2026", practical: "Everything you need, in one calm place.", checklistSub: "Your progress stays safely on this device.", emergency: "Emergency in Türkiye",
    shareLocation: "Share my current location", contactPending: "Event coordinator · details to be updated", weather: "Weather", weatherText: "Live forecast will appear closer to travel.",
    currency: "Currency", currencyText: "Turkish lira (TRY)", timezone: "Time zone", timezoneText: "UTC+3 · same as Amman during the event", power: "Power", powerText: "Bring a universal travel adapter.",
    greeting: "Dear Doctor", signoff: "Warmest regards,\nDar Aldawa", galleryText: "Daily highlights and approved event photos will appear here during the journey.", soon: "Coming during the event", source: "Practical information sources",
  },
  ar: {
    start: "ابدأ التجربة", opening: "تجربتك في إسطنبول تبدأ من هنا", welcome: "أهلاً بك في رحلة يجتمع فيها العلم والتواصل وسحر إسطنبول.", explore: "استعرض البرنامج", calendar: "أضف الحدث إلى التقويم",
    days: "أيام", talks: "محاضرات علمية", city: "المدينة", stay: "إقامتك", letter: "رسالة الترحيب", journey: "رحلتنا تبدأ من هنا", program: "جدولنا المميز", science: "الندوة العلمية",
    speakers: "نخبة العلم", locations: "معنا ما راح تضيع", hotel: "إقامتك بكل راحة", before: "كل ما تحتاجه قبل السفر", essentials: "دليلك في إسطنبول", support: "نحن دائماً معك", faq: "الأسئلة الشائعة",
    gallery: "لحظاتنا معاً", home: "التجربة", note: "البرنامج مؤكد · ستتم مشاركة تفاصيل الطيران والتواصل قريباً", download: "تحميل الرسالة الأصلية", close: "إغلاق", route: "فتح في خرائط Google",
    share: "شارك التجربة", print: "حفظ البرنامج PDF", flightPending: "سيتم تحديث تفاصيل الرحلة", outbound: "رحلة الذهاب", return: "رحلة العودة", origin: "الأردن", destination: "إسطنبول",
    eventDay: "الأربعاء · 16 سبتمبر 2026", practical: "كل ما تحتاجه في مكان واحد وبكل وضوح.", checklistSub: "يتم حفظ تقدمك على هذا الجهاز.", emergency: "الطوارئ في تركيا",
    shareLocation: "مشاركة موقعي الحالي", contactPending: "منسق الحدث · سيتم تحديث البيانات", weather: "الطقس", weatherText: "سيظهر التوقع المباشر عند اقتراب موعد السفر.", currency: "العملة",
    currencyText: "الليرة التركية (TRY)", timezone: "التوقيت", timezoneText: "UTC+3 · نفس توقيت عمّان خلال الحدث", power: "الكهرباء", powerText: "يفضل إحضار محول سفر عالمي.", greeting: "طبيبنا العزيز",
    signoff: "مع أطيب التحيات،\nدار الدواء", galleryText: "ستظهر هنا أبرز اللحظات والصور المعتمدة يومياً خلال الرحلة.", soon: "قريباً خلال الحدث", source: "مصادر المعلومات العملية",
  },
};

const typeIcon = { travel: "↗", dining: "◇", science: "+", social: "✦", hotel: "⌂", free: "○" };

export default function Home() {
  const [lang, setLang] = useState<Lang>("en"), [started, setStarted] = useState(false), [letterOpen, setLetterOpen] = useState(false), [day, setDay] = useState(0);
  const [checked, setChecked] = useState<number[]>([]), [menu, setMenu] = useState(false), [remaining, setRemaining] = useState(""), [guestName, setGuestName] = useState("");
  const t = copy[lang];
  useEffect(() => {
    const savedLang = localStorage.getItem("first-lang") as Lang | null; if (savedLang === "ar" || savedLang === "en") setLang(savedLang);
    const saved = localStorage.getItem("first-checklist"); if (saved) setChecked(JSON.parse(saved));
    const n = new URLSearchParams(window.location.search).get("name"); if (n) setGuestName(n.slice(0, 60));
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined);
  }, []);
  useEffect(() => { document.documentElement.lang = lang; document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"; localStorage.setItem("first-lang", lang); }, [lang]);
  useEffect(() => { const tick = () => { const diff = Math.max(0, new Date(event.start).getTime() - Date.now()); const d = Math.floor(diff/86400000), h = Math.floor((diff/3600000)%24), m = Math.floor((diff/60000)%60); setRemaining(diff ? (lang === "ar" ? `${d} يوم · ${h} ساعة · ${m} دقيقة` : `${d} days · ${h} hrs · ${m} min`) : (lang === "ar" ? "بدأت التجربة" : "The experience has begun")); }; tick(); const id=setInterval(tick,60000); return()=>clearInterval(id); }, [lang]);
  useEffect(() => { const nodes = document.querySelectorAll(".section,.istanbul-page,.restaurants-page,.contacts-page,.gallery-section"); nodes.forEach(n=>n.classList.add("motion-section")); const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in-view");observer.unobserve(e.target)}}),{threshold:.08}); nodes.forEach(n=>observer.observe(n)); return()=>observer.disconnect(); }, [started]);
  const nav = useMemo(() => [["home",t.home,"01"],["journey",t.journey,"02"],["program",t.program,"03"],["speakers",t.speakers,"04"],["locations",t.locations,"05"],["istanbul",lang==="ar"?"إسطنبول معنا غير":"Istanbul, Our Way","06"],["restaurants",lang==="ar"?"مذاقات إسطنبول":"Dining Journal","07"],["before",t.before,"08"],["support",t.support,"09"]], [t,lang]);
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
  const toggleCheck=(i:number)=>{const next=checked.includes(i)?checked.filter(x=>x!==i):[...checked,i];setChecked(next);localStorage.setItem("first-checklist",JSON.stringify(next))};
  const sharePage=async()=>{const data={title:"FIRST Istanbul Experience",text:`${event.tagline} · ${event.dates}`,url:location.href};if(navigator.share)await navigator.share(data).catch(()=>undefined);else await navigator.clipboard.writeText(location.href)};
  const shareLocation=()=>navigator.geolocation?.getCurrentPosition(({coords})=>{const msg=encodeURIComponent(`My current location: https://maps.google.com/?q=${coords.latitude},${coords.longitude}`);window.open(`https://wa.me/?text=${msg}`,"_blank","noopener,noreferrer")});

  const countdownParts = remaining.includes("·") ? remaining.split("·").map(x=>x.trim()) : [remaining];
  return <main className="site-shell">
    <div className={`opening opening--theme ${started?"opening--closed":""}`} aria-hidden={started}><div className="opening-countdown"><span>{lang==="ar"?"متبقي على التجربة":"UNTIL THE EXPERIENCE"}</span><div className="opening-countdown-units">{countdownParts.map(part=>{const [value,...label]=part.split(" ");return <strong key={part}><b>{value}</b><small>{label.join(" ")}</small></strong>})}</div></div><button className="opening-enter" aria-label={t.start} onClick={()=>setStarted(true)}><span>{t.start}</span><i>→</i></button></div>
    {menu&&<button className="menu-backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
    <aside className={`sidebar floating-dropdown ${menu?"sidebar--open":""}`}><div className="floating-menu-head"><img src="/assets/dar-aldawa-logo-transparent.png" alt="Dar Aldawa"/><b>FIRST · ISTANBUL 2026</b><button aria-label="Close menu" onClick={()=>setMenu(false)}>×</button></div><nav>{nav.map(([id,label,num])=><button key={id} onClick={()=>go(id)}><span>{num}</span>{label}</button>)}</nav><div className="sidebar-foot"><span>15—18 SEPTEMBER</span><button className="lang" onClick={()=>setLang(lang==="en"?"ar":"en")}>{lang==="en"?"ع":"EN"}</button></div></aside>
    <button className={`floating-menu-button ${menu?"is-open":""}`} onClick={()=>setMenu(v=>!v)} aria-label={menu?"Close navigation":"Open navigation"}><span/><span/><span/><b>{lang==="ar"?"القائمة":"MENU"}</b></button>
    <div className="page"><header className="mobile-header"><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open menu">☰</button><img className="first-logo first-logo--mobile" src="/assets/first-logo.png" alt="FIRST"/><button className="lang" onClick={()=>setLang(lang==="en"?"ar":"en")}>{lang==="en"?"ع":"EN"}</button></header>
      <section id="home" className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="hero-content reveal"><p className="eyebrow">DAR ALDAWA PRESENTS · ISTANBUL 2026</p><h1><span>FIRST</span><small>{event.tagline}</small></h1><p className="hero-welcome">{guestName?`${lang==="ar"?"أهلاً بك دكتور":"Welcome, Dr."} ${guestName}`:t.welcome}</p><div className="hero-actions"><button className="button button--bright" onClick={()=>go("program")}>{t.explore}</button><a className="button button--glass" href="/FIRST-Istanbul-2026.ics">{t.calendar}</a></div></div><button className="scroll-cue" onClick={()=>go("journey")}><span/>SCROLL</button></section>
      <section id="journey" className="section section--light"><SectionHead index="02" kicker="AMMAN → ISTANBUL" title={t.journey} sub={t.practical}/><div className="boarding-grid">{[{label:t.outbound,from:t.origin,to:t.destination,date:"15 SEP 2026"},{label:t.return,from:t.destination,to:"AMMAN",date:"18 SEP 2026"}].map((f,i)=><article className="boarding" key={f.label}><div className="boarding-top"><span>{f.label}</span><b>FIRST / 0{i+1}</b></div><div className="boarding-route"><div><small>FROM</small><strong>{f.from}</strong></div><div className="route-line"><span>✈</span></div><div><small>TO</small><strong>{f.to}</strong></div></div><div className="boarding-meta"><div><small>DATE</small><b>{f.date}</b></div><div><small>FLIGHT</small><b>TBC</b></div><div><small>TIME</small><b>TBC</b></div><div><small>BAGGAGE</small><b>TBC</b></div></div><p>{t.flightPending}</p></article>)}</div><div className="arrival-note"><span>13</span><div><b>{lang==="ar"?"نقطة اللقاء عند الوصول":"Arrival meeting point"}</b><p>{lang==="ar"?"الاستقبال من بوابة رقم 13 بين 11:30 و12:30":"Airport pick-up at Gate 13 between 11:30 and 12:30"}</p></div></div></section>
      <section id="program" className="section section--dark calendar-program"><SectionHead index="03" kicker="15—18 SEPTEMBER" title={t.program} sub={lang==="ar"?"اختر التاريخ لتفتح صفحة ذلك اليوم.":"Choose a date to open that day’s calendar page."}/><div className="day-tabs calendar-tabs" role="tablist">{days.map((d,i)=><button className={day===i?"active":""} onClick={()=>setDay(i)} key={d.date}><span>{d.date.split(" ")[0]}</span><b>{d.date.split(" ")[1]}</b><small>{d.label[lang]}</small><i>0{i+1}</i></button>)}</div><div className="calendar-page" key={day}><div className="calendar-page-head"><span>DAY 0{day+1}</span><div><b>{days[day].date}</b><small>{days[day].label[lang]}</small></div></div><div className="timeline">{days[day].activities.map((a,i)=><article className={`timeline-item type-${a.type}`} key={`${a.time}-${i}`}><div className="time">{a.time}</div><div className="timeline-dot">{typeIcon[a.type]}</div><div className="activity"><b>{a[lang]}</b><small>{a.type.toUpperCase()}</small>{a.map&&<a href={a.map} target="_blank" rel="noreferrer">{t.route} ↗</a>}</div></article>)}</div></div><div className="program-actions"><a className="button button--bright" href="/FIRST-Istanbul-2026.ics">{t.calendar}</a><button className="button button--outline" onClick={()=>window.print()}>{t.print}</button></div><div className="print-all">{days.map(d=><div key={d.date}><h3>{d.date} · {d.label[lang]}</h3>{d.activities.map((a,ai)=><p key={ai}><b>{a.time}</b> — {a[lang]}</p>)}</div>)}</div></section>
      <section id="science" className="section section--mint"><SectionHead index="03A" kicker={t.eventDay} title={t.science} sub="Crystal Ballroom · M2 Floor"/><div className="science-wrap"><div className="science-list">{scienceAgenda.map((a,i)=><div className="science-row" key={i}><time>{a.time}</time><span>{a[lang]}</span></div>)}</div><button className="agenda-poster" onClick={()=>window.open("/assets/scientific-agenda.jpg","_blank")}><img src="/assets/scientific-agenda.jpg" alt="Scientific symposium agenda"/><span>{lang==="ar"?"عرض الأجندة الأصلية":"View original agenda"} ↗</span></button></div></section>
      <section id="speakers" className="section section--light"><SectionHead index="04" kicker="DISTINGUISHED FACULTY" title={t.speakers} sub={lang==="ar"?"خبرات تجمع بين الممارسة السريرية والدليل العلمي.":"Clinical leadership meets evidence-led practice."}/><div className="speakers-grid"><Speaker side="left" accent="coral" name="Dr. Suliman Soudi" role={lang==="ar"?"استشاري الأنف والأذن والحنجرة":"Ear, Nose & Throat Consultant"} title="GERD Management: Broadening Recognition, Enhancing Care" bullets={lang==="ar"?["استشاري أنف وأذن وحنجرة","سابقاً في الخدمات الطبية الملكية","زميل الكلية الملكية للجراحين، المملكة المتحدة","دبلوم جراحة الأذن وزراعة القوقعة، أوكلاهوما","بكالوريوس الطب والجراحة، ليفربول"]:["Consultant Ear, Nose and Throat","Formerly at Royal Medical Services","Fellow of the Royal College of Surgeons, UK","Diploma in Ear & Cochlear Implant Surgery, Oklahoma","Bachelor of Medicine and Surgery, Liverpool"]}/><Speaker side="right" accent="teal" name="Dr. Feras Zuriekat, MD, MRCP (UK)" role={lang==="ar"?"استشاري أمراض الجهاز الهضمي والكبد":"Consultant in Gastroenterology & Hepatology"} title="GERD Management: Integrating Evidence, Optimizing Outcomes" bullets={lang==="ar"?["رئيس قسم الجهاز الهضمي والكبد في مستشفى العبدلي","خريج كلية الطب بجامعة دندي عام 1995","حصل على جائزة أفضل طالب وافد","عضو الكلية الملكية للأطباء MRCP (UK) منذ 2001"]:["Head of Gastroenterology & Hepatology at Abdali Hospital","University of Dundee Medical School graduate, 1995","Prize for Best Overseas Student","MRCP (UK), 2001"]}/></div></section>
      <section id="locations" className="section section--navy"><SectionHead index="05" kicker="YOUR ISTANBUL MAP" title={t.locations} sub={lang==="ar"?"كل مكان في البرنامج، على بُعد ضغطة واحدة.":"Every programme location, one tap away."}/><div className="location-grid">{locations.map((l,i)=><a className="location-card" href={l.map} target="_blank" rel="noreferrer" key={l.en}><span className={`pin pin--${l.kind}`}>0{i+1}</span><div><small>{l.kind.toUpperCase()}</small><b>{l[lang]}</b><em>{t.route} ↗</em></div></a>)}</div></section>
      <IstanbulSection lang={lang}/>
      <RestaurantsSection lang={lang}/>
      <section id="before" className="section section--light"><SectionHead index="07" kicker="TRAVEL READY" title={t.before} sub={t.checklistSub}/><div className="checklist"><div className="check-progress"><span style={{width:`${Math.round(checked.length/checklist.length*100)}%`}}/><b>{checked.length}/{checklist.length}</b></div>{checklist.map((item,i)=><button className={checked.includes(i)?"done":""} onClick={()=>toggleCheck(i)} key={item.en}><span>{checked.includes(i)?"✓":String(i+1).padStart(2,"0")}</span><b>{item[lang]}</b></button>)}</div></section>
      <ContactsSection lang={lang} onShareLocation={shareLocation}/>
      <section id="faq" className="section section--light"><SectionHead index="09" kicker="GOOD TO KNOW" title={t.faq} sub={lang==="ar"?"إجابات مختصرة لأكثر الأسئلة شيوعاً.":"Fast answers to the questions that matter."}/><div className="faq">{(lang==="ar"?[["أين وموعد التجمع عند الوصول؟","الاستقبال من بوابة رقم 13 في المطار من 11:30 إلى 12:30 يوم 15 سبتمبر."],["متى تُقام الندوة العلمية؟","يوم الأربعاء 16 سبتمبر في قاعة Crystal، طابق M2. يبدأ التسجيل 09:30 والندوة 10:00."],["هل تشمل الدعوة المصاريف الشخصية؟","تغطي دار الدواء الإقامة والأنشطة المجدولة. المكالمات والغسيل وخدمة الغرف والميني بار غير مشمولة."],["متى نحصل على تفاصيل الطيران والتواصل؟","ستُحدّث الصفحة فور اعتماد رقم الرحلة والأوقات وبيانات منسق الحدث."],["هل يمكنني استخدام الموقع دون إنترنت؟","بعد فتح الموقع مرة واحدة، يمكن الوصول إلى المحتوى الأساسي عند ضعف الاتصال."]]:[["Where and when is the arrival meeting point?","Airport pick-up is at Gate 13 from 11:30 to 12:30 on 15 September."],["When is the scientific symposium?","Wednesday, 16 September in Crystal Ballroom, M2. Registration starts at 09:30; the symposium at 10:00."],["Are personal expenses covered?","Dar Aldawa covers your stay and programmed activities. Calls, laundry, room service and minibar charges are not covered."],["When will flight and contact details be available?","This page will be updated as soon as flight numbers, times and coordinator details are confirmed."],["Can I access the site with weak internet?","After your first visit, key content can remain available when connectivity is limited."]]).map(([q,a],i)=><details key={i}><summary><span>0{i+1}</span>{q}</summary><p>{a}</p></details>)}</div></section>
      <section id="gallery" className="gallery-section"><div className="gallery-copy"><span className="eyebrow">MEMORIES IN THE MAKING</span><h2>{t.gallery}</h2><p>{t.galleryText}</p><span className="soon-chip">{t.soon}</span></div><div className="gallery-grid"><div/><div/><div/><div/></div></section>
      <footer><div className="footer-brand"><img src="/assets/dar-aldawa-logo-transparent.png" alt="Dar Aldawa"/><b>FIRST · Steps to Effective Treatment</b></div><p>15—18 SEPTEMBER 2026 · ISTANBUL</p><div className="footer-actions"><button onClick={sharePage}>{t.share}</button><button onClick={()=>setLetterOpen(true)}>{t.letter}</button></div><div className="sources"><span>{t.source}:</span><a href="https://www.112.gov.tr/" target="_blank" rel="noreferrer">Türkiye 112</a><a href="https://www.timeanddate.com/time/zone/turkey/istanbul" target="_blank" rel="noreferrer">Istanbul time</a></div></footer>
    </div>
    <div className="quick-help"><a href="tel:112" aria-label="Emergency call 112">112</a><button onClick={shareLocation} aria-label="Share location">⌖</button></div><nav className="bottom-nav"><button onClick={()=>go("home")}>⌂<span>{t.home}</span></button><button onClick={()=>go("program")}>☷<span>{t.program}</span></button><button onClick={()=>go("locations")}>⌖<span>{t.locations}</span></button><button onClick={()=>go("support")}>＋<span>{t.support}</span></button></nav>
    {letterOpen&&<div className="modal" role="dialog" aria-modal="true" aria-label={t.letter}><button className="modal-backdrop" onClick={()=>setLetterOpen(false)} aria-label={t.close}/><div className="letter"><button className="letter-close" onClick={()=>setLetterOpen(false)}>×</button><span className="letter-number">FIRST · 2026</span><h2>{guestName?`${t.greeting} ${guestName},`:`${t.greeting},`}</h2>{lang==="ar"?<><p>يسرّ دار الدواء أن ترحب بكم في الندوة العلمية <b>FIRST — خطوات نحو العلاج الفعّال.</b></p><p>تهدف هذه الندوة إلى جمع نخبة من المهنيين الطبيين أمثالكم، وتوفير منصة مميزة للتعاون وتبادل المعرفة.</p><p>يسرّ دار الدواء تغطية تكاليف إقامتكم والأنشطة المدرجة ضمن البرنامج. أما المصاريف الشخصية مثل المكالمات الهاتفية والغسيل وخدمة الغرف والميني بار، فلا تشملها التغطية.</p></>:<><p>Dar Aldawa is delighted to welcome you to the scientific symposium entitled <b>FIRST — Steps to Effective Treatment.</b></p><p>This scientific symposium brings together distinguished medical professionals like you, providing a unique platform for collaboration and knowledge exchange.</p><p>Dar Aldawa is pleased to cover the cost of your stay and programmed activities. Personal expenses such as phone calls, laundry, in-room service and minibar charges are not covered by Dar Aldawa.</p></>}<p className="signature">{t.signoff.split("\n").map((x,i)=><span key={i}>{x}</span>)}</p><div className="letter-actions"><a href="/assets/welcome-letter.png" download>{t.download}</a><button onClick={()=>setLetterOpen(false)}>{t.close}</button></div></div></div>}
  </main>;
}

function SectionHead({index,kicker,title,sub}:{index:string;kicker:string;title:string;sub:string}){return <div className="section-head"><span className="section-index">{index}</span><div><small>{kicker}</small><h2>{title}</h2><p>{sub}</p></div></div>}
function Speaker({side,accent,name,role,title,bullets}:{side:"left"|"right";accent:string;name:string;role:string;title:string;bullets:string[]}){return <article className={`speaker speaker--${accent}`}><div className={`speaker-photo speaker-photo--${side}`}><img src={side==="left"?"/assets/dr-suliman-soudi.jpg":"/assets/dr-feras-zuriekat.jpg"} alt={name}/></div><div className="speaker-copy"><span>FIRST FACULTY</span><h3>{name}</h3><p className="speaker-role">{role}</p><blockquote>“{title}”</blockquote><ul>{bullets.map(b=><li key={b}>{b}</li>)}</ul></div></article>}
